apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: cat-auth
---
apiVersion: v1
kind: Pod
metadata:
  name: cat-nginx
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'cat_kubernetes_role'
    vault.hashicorp.com/agent-inject-secret-config.txt: 'cat-kv-v2/credentials'
    vault.hashicorp.com/agent-inject-template-config.txt: |
      {{ with secret "cat-kv-v2/credentials" -}}
        Address=127.0.0.1
        Port=3306
        Pass: {{ .Data.data.password }}
        User: {{ .Data.data.user }}
      {{- end }}
    vault.hashicorp.com/agent-inject-secret-envs: 'cat-kv-v2/secrets'
    vault.hashicorp.com/agent-inject-template-envs: |
      {{ with secret "cat-kv-v2/secrets" -}}
        export CAT_SECRET="{{ .Data.data.secret }}"
      {{- end }}
spec:
  containers:
    - image: nginx:latest
      name: nginx
      command: ['/bin/bash']
      args: ['-c', 'source /vault/secrets/envs && env > /vault/secrets/test && tail -f /dev/null' ]
  serviceAccountName: cat-auth